"""filters

Revision ID: 57f3b01142f5
Revises: c26262be7756
Create Date: 2018-02-12 20:54:34.339326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f3b01142f5'
down_revision = 'c26262be7756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_course_code'), 'filter', ['course_code'], unique=False)
    op.drop_index('ix_user_cal_url', table_name='user')
    op.drop_index('ix_user_client_id', table_name='user')
    op.drop_index('ix_user_client_secret', table_name='user')
    op.drop_index('ix_user_refresh_token', table_name='user')
    op.drop_index('ix_user_scopes', table_name='user')
    op.drop_index('ix_user_token', table_name='user')
    op.drop_index('ix_user_token_uri', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_token_uri', 'user', ['token_uri'], unique=False)
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.create_index('ix_user_scopes', 'user', ['scopes'], unique=False)
    op.create_index('ix_user_refresh_token', 'user', ['refresh_token'], unique=False)
    op.create_index('ix_user_client_secret', 'user', ['client_secret'], unique=False)
    op.create_index('ix_user_client_id', 'user', ['client_id'], unique=False)
    op.create_index('ix_user_cal_url', 'user', ['cal_url'], unique=False)
    op.drop_index(op.f('ix_filter_course_code'), table_name='filter')
    op.drop_table('filter')
    # ### end Alembic commands ###
