"""users table

Revision ID: c26262be7756
Revises: 
Create Date: 2018-02-12 20:07:45.308109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26262be7756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cal_id', sa.String(length=80), nullable=True),
    sa.Column('cal_url', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=150), nullable=True),
    sa.Column('refresh_token', sa.String(length=80), nullable=True),
    sa.Column('token_uri', sa.String(length=80), nullable=True),
    sa.Column('client_id', sa.String(length=120), nullable=True),
    sa.Column('client_secret', sa.String(length=80), nullable=True),
    sa.Column('scopes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cal_id'), 'user', ['cal_id'], unique=False)
    op.create_index(op.f('ix_user_cal_url'), 'user', ['cal_url'], unique=False)
    op.create_index(op.f('ix_user_client_id'), 'user', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_client_secret'), 'user', ['client_secret'], unique=False)
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_scopes'), 'user', ['scopes'], unique=False)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=False)
    op.create_index(op.f('ix_user_token_uri'), 'user', ['token_uri'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token_uri'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_scopes'), table_name='user')
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    op.drop_index(op.f('ix_user_client_secret'), table_name='user')
    op.drop_index(op.f('ix_user_client_id'), table_name='user')
    op.drop_index(op.f('ix_user_cal_url'), table_name='user')
    op.drop_index(op.f('ix_user_cal_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
