"""empty message

Revision ID: db3941530d75
Revises: 57f3b01142f5
Create Date: 2018-03-15 19:47:04.943581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3941530d75'
down_revision = '57f3b01142f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=False)
    op.drop_index('ix_user_cal_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_cal_id', 'user', ['cal_id'], unique=False)
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
